// Sample applicant data for the Vendor Application Review queue.
// `appliedHoursAgo` keeps the demo fresh relative to the current time.

const LANGUAGES = {
  AR: "Arabic", CS: "Czech", DE: "German", EN: "English", ES: "Spanish",
  FR: "French", HI: "Hindi", IT: "Italian", JA: "Japanese", KO: "Korean",
  NO: "Norwegian", PL: "Polish", PT: "Portuguese", SV: "Swedish", TA: "Tamil",
  UR: "Urdu", YO: "Yoruba", ZH: "Chinese (Trad.)",
};

const VENDORS = [
  {
    id: "APP-2041", name: "Sofia Martínez", email: "sofia.martinez@protonmail.com",
    location: "Madrid, Spain", timezone: "CET (UTC+1)", appliedHoursAgo: 2,
    pairs: ["EN>ES", "PT>ES"], specs: ["Legal", "Financial"], years: 9, rate: 0.12,
    capacity: 12000, tools: ["Trados Studio", "memoQ", "Xbench"], score: 94,
    verification: { identity: "verified", ata: "verified", degree: "verified" },
    ataNumber: "ATA-284715", status: "pending",
    summary: "Sworn translator (MAEC) specialising in cross-border contracts, M&A due diligence and annual reports. Former in-house linguist at a Big Four firm; comfortable with tight turnarounds and complex terminology management.",
    education: { degree: "MA Legal & Financial Translation", school: "Universidad Complutense de Madrid", year: 2015 },
    history: [
      { role: "Freelance Legal Translator", org: "Self-employed", from: 2019, to: null },
      { role: "In-house Translator", org: "Deloitte Spain", from: 2015, to: 2019 },
    ],
  },
  {
    id: "APP-2040", name: "Kenji Watanabe", email: "k.watanabe@outlook.jp",
    location: "Osaka, Japan", timezone: "JST (UTC+9)", appliedHoursAgo: 5,
    pairs: ["JA>EN", "EN>JA"], specs: ["Technical", "Gaming"], years: 14, rate: 0.14,
    capacity: 15000, tools: ["memoQ", "Phrase", "Smartcat"], score: 91,
    verification: { identity: "verified", ata: "verified", degree: "pending" },
    ataNumber: "ATA-199302", status: "pending",
    summary: "Bidirectional JA⇄EN localizer with 14 years across console titles and semiconductor documentation. Led localization QA for two AAA releases and maintains a 40k-entry gaming glossary.",
    education: { degree: "BA English Literature", school: "Kyoto University", year: 2010 },
    history: [
      { role: "Lead Localization Specialist", org: "Freelance", from: 2017, to: null },
      { role: "Localization QA", org: "Square Enix", from: 2010, to: 2017 },
    ],
  },
  {
    id: "APP-2039", name: "Yuna Park", email: "yuna.park@gmail.com",
    location: "Seoul, South Korea", timezone: "KST (UTC+9)", appliedHoursAgo: 6,
    pairs: ["KO>EN", "EN>KO"], specs: ["Gaming", "Marketing"], years: 6, rate: 0.11,
    capacity: 10000, tools: ["Trados Studio", "Crowdin"], score: 90,
    verification: { identity: "verified", ata: "pending", degree: "verified" },
    ataNumber: "ATA-310044", status: "pending",
    summary: "Transcreation specialist for mobile games and K-beauty brands. Strong copywriting voice in both directions; experienced with live-ops content pipelines and string-length constraints.",
    education: { degree: "MA Interpretation & Translation", school: "Hankuk University of Foreign Studies", year: 2018 },
    history: [
      { role: "Game Localizer", org: "Netmarble (contract)", from: 2021, to: null },
      { role: "Marketing Translator", org: "Amorepacific", from: 2018, to: 2021 },
    ],
  },
  {
    id: "APP-2038", name: "Amara Okafor", email: "amara.okafor@yahoo.com",
    location: "Lagos, Nigeria", timezone: "WAT (UTC+1)", appliedHoursAgo: 9,
    pairs: ["EN>FR", "EN>YO"], specs: ["Medical", "NGO"], years: 6, rate: 0.08,
    capacity: 9000, tools: ["Phrase", "Wordfast"], score: 86,
    verification: { identity: "verified", ata: "none", degree: "verified" },
    ataNumber: null, status: "pending",
    summary: "Public-health translator for WHO and MSF field programmes. Specialises in patient-facing materials, informed consent forms and community outreach content for West African audiences.",
    education: { degree: "BSc Nursing; Dipl. Translation", school: "University of Lagos", year: 2017 },
    history: [
      { role: "Medical Translator", org: "Médecins Sans Frontières", from: 2020, to: null },
      { role: "Community Health Officer", org: "Lagos State MoH", from: 2017, to: 2020 },
    ],
  },
  {
    id: "APP-2037", name: "Mateo Fernández", email: "mateo.fdz@gmail.com",
    location: "Buenos Aires, Argentina", timezone: "ART (UTC−3)", appliedHoursAgo: 12,
    pairs: ["EN>ES"], specs: ["Financial", "Legal"], years: 3, rate: 0.07,
    capacity: 8000, tools: ["Trados Studio"], score: 80,
    verification: { identity: "verified", ata: "none", degree: "verified" },
    ataNumber: null, status: "pending",
    summary: "Certified public translator (CTPCBA) focused on LATAM Spanish for fintech terms of service, KYC documentation and investor reports.",
    education: { degree: "Traductor Público (EN)", school: "Universidad de Buenos Aires", year: 2021 },
    history: [
      { role: "Financial Translator", org: "Mercado Pago (vendor)", from: 2022, to: null },
      { role: "Junior Translator", org: "Estudio Beccar Varela", from: 2021, to: 2022 },
    ],
  },
  {
    id: "APP-2036", name: "Lukas Becker", email: "lukas.becker@posteo.de",
    location: "Berlin, Germany", timezone: "CET (UTC+1)", appliedHoursAgo: 26,
    pairs: ["DE>EN", "EN>DE"], specs: ["Technical", "Automotive"], years: 11, rate: 0.13,
    capacity: 14000, tools: ["Trados Studio", "memoQ", "Across"], score: 89,
    verification: { identity: "verified", ata: "verified", degree: "verified" },
    ataNumber: "ATA-221870", status: "pending",
    summary: "Mechanical engineer turned technical translator. Owner's manuals, service documentation and ISO 26262 safety cases for German OEMs and Tier-1 suppliers.",
    education: { degree: "Dipl.-Ing. Mechanical Engineering", school: "TU Berlin", year: 2012 },
    history: [
      { role: "Technical Translator", org: "Freelance", from: 2015, to: null },
      { role: "Design Engineer", org: "Bosch", from: 2012, to: 2015 },
    ],
  },
  {
    id: "APP-2035", name: "Mei Lin Chen", email: "meilin.chen@gmail.com",
    location: "Taipei, Taiwan", timezone: "CST (UTC+8)", appliedHoursAgo: 31,
    pairs: ["ZH>EN"], specs: ["Marketing", "Gaming"], years: 4, rate: 0.09,
    capacity: 7000, tools: ["Phrase", "Smartcat"], score: 78,
    verification: { identity: "pending", ata: "none", degree: "verified" },
    ataNumber: null, status: "pending",
    summary: "Creative translator for consumer electronics launches and indie games. Native-level English copy with strong cultural adaptation for North American audiences.",
    education: { degree: "BA Foreign Languages & Literature", school: "National Taiwan University", year: 2020 },
    history: [
      { role: "Marketing Translator", org: "ASUS (agency)", from: 2021, to: null },
      { role: "Localization Intern", org: "Gamania", from: 2020, to: 2021 },
    ],
  },
  {
    id: "APP-2034", name: "Rafael Costa", email: "rafael.costa@uol.com.br",
    location: "São Paulo, Brazil", timezone: "BRT (UTC−3)", appliedHoursAgo: 50,
    pairs: ["EN>PT", "ES>PT"], specs: ["Legal"], years: 2, rate: 0.06,
    capacity: 6000, tools: ["Wordfast"], score: 72,
    verification: { identity: "verified", ata: "none", degree: "pending" },
    ataNumber: null, status: "pending",
    summary: "Law graduate translating contracts and court filings into Brazilian Portuguese. Looking to grow volume with an agency partner.",
    education: { degree: "LLB (Bacharel em Direito)", school: "Universidade de São Paulo", year: 2022 },
    history: [
      { role: "Legal Translator", org: "Freelance", from: 2022, to: null },
    ],
  },
  {
    id: "APP-2033", name: "Tariq Hussain", email: "tariq.hussain@hotmail.com",
    location: "Karachi, Pakistan", timezone: "PKT (UTC+5)", appliedHoursAgo: 54,
    pairs: ["UR>EN", "EN>UR"], specs: ["Legal", "NGO"], years: 5, rate: 0.06,
    capacity: 9000, tools: ["Trados Studio", "Smartcat"], score: 70,
    verification: { identity: "pending", ata: "none", degree: "pending" },
    ataNumber: null, status: "pending",
    summary: "Asylum and immigration document translator working with UNHCR implementing partners. Experienced in affidavits, civil records and interview transcripts.",
    education: { degree: "MA English Linguistics", school: "University of Karachi", year: 2019 },
    history: [
      { role: "Translator", org: "UNHCR implementing partner", from: 2020, to: null },
      { role: "Court Interpreter (part-time)", org: "Sindh High Court", from: 2019, to: 2020 },
    ],
  },
  {
    id: "APP-2032", name: "Omar Haddad", email: "omar.haddad@gmail.com",
    location: "Amman, Jordan", timezone: "AST (UTC+3)", appliedHoursAgo: 72,
    pairs: ["AR>EN", "EN>AR"], specs: ["Medical", "Legal"], years: 16, rate: 0.15,
    capacity: 16000, tools: ["Trados Studio", "memoQ", "Phrase"], score: 97,
    verification: { identity: "verified", ata: "verified", degree: "verified" },
    ataNumber: "ATA-150228", status: "pending",
    summary: "Senior medical and legal linguist with 16 years of clinical trial documentation (ICFs, protocols, CRFs) and international arbitration work. Reviewer for two pharma sponsors' linguistic validation programmes.",
    education: { degree: "MA Translation Studies", school: "University of Jordan", year: 2008 },
    history: [
      { role: "Senior Linguist & Reviewer", org: "Freelance", from: 2014, to: null },
      { role: "Medical Translator", org: "King Hussein Cancer Center", from: 2008, to: 2014 },
    ],
  },
  {
    id: "APP-2031", name: "Hana Novák", email: "hana.novak@seznam.cz",
    location: "Prague, Czechia", timezone: "CET (UTC+1)", appliedHoursAgo: 80,
    pairs: ["CS>EN", "DE>EN"], specs: ["Financial"], years: 8, rate: 0.1,
    capacity: 11000, tools: ["memoQ", "Xbench"], score: 88,
    verification: { identity: "failed", ata: "pending", degree: "verified" },
    ataNumber: "ATA-298811", status: "info",
    infoRequest: "Identity document image was blurred — please re-upload a clear scan of your passport.",
    summary: "Financial translator for Central European banks: IFRS statements, prospectuses and ESG disclosures. Native Czech, near-native German, translating into English.",
    education: { degree: "MA Translation (EN/DE)", school: "Charles University", year: 2016 },
    history: [
      { role: "Financial Translator", org: "Freelance", from: 2018, to: null },
      { role: "Analyst", org: "Komerční banka", from: 2016, to: 2018 },
    ],
  },
  {
    id: "APP-2030", name: "Priya Raman", email: "priya.raman@gmail.com",
    location: "Chennai, India", timezone: "IST (UTC+5:30)", appliedHoursAgo: 96,
    pairs: ["EN>TA", "EN>HI"], specs: ["Technical", "E-learning"], years: 7, rate: 0.07,
    capacity: 12000, tools: ["Phrase", "Smartcat", "Crowdin"], score: 82,
    verification: { identity: "verified", ata: "none", degree: "verified" },
    ataNumber: null, status: "pending",
    summary: "Localizes SaaS UI, help centres and corporate training into Tamil and Hindi. Comfortable with subtitle timing and Articulate Storyline packages.",
    education: { degree: "MA Linguistics", school: "University of Madras", year: 2016 },
    history: [
      { role: "Localization Specialist", org: "Freshworks (vendor)", from: 2019, to: null },
      { role: "Content Translator", org: "BYJU'S", from: 2017, to: 2019 },
    ],
  },
  {
    id: "APP-2029", name: "Élodie Laurent", email: "elodie.laurent@orange.fr",
    location: "Lyon, France", timezone: "CET (UTC+1)", appliedHoursAgo: 100,
    pairs: ["EN>FR"], specs: ["Marketing"], years: 5, rate: 0.11,
    capacity: 8000, tools: ["Trados Studio", "Phrase"], score: 84,
    verification: { identity: "verified", ata: "pending", degree: "verified" },
    ataNumber: "ATA-305512", status: "info",
    infoRequest: "Please share two transcreation samples from luxury or fashion campaigns.",
    summary: "Transcreation and copy adaptation for luxury, beauty and hospitality brands. Strong SEO background and brand-voice consistency across campaigns.",
    education: { degree: "Master ISIT Translation", school: "ISIT Paris", year: 2019 },
    history: [
      { role: "Transcreator", org: "Freelance", from: 2021, to: null },
      { role: "Copywriter", org: "Publicis Lyon", from: 2019, to: 2021 },
    ],
  },
  {
    id: "APP-2028", name: "Giulia Romano", email: "giulia.romano@libero.it",
    location: "Bologna, Italy", timezone: "CET (UTC+1)", appliedHoursAgo: 120,
    pairs: ["IT>EN", "EN>IT"], specs: ["Medical", "Life Sciences"], years: 12, rate: 0.13,
    capacity: 13000, tools: ["Trados Studio", "memoQ"], score: 93,
    verification: { identity: "verified", ata: "verified", degree: "verified" },
    ataNumber: "ATA-176604", status: "approved",
    summary: "Life-sciences translator: IFUs, regulatory submissions (EMA/AIFA) and medical device labelling. ISO 17100-qualified with a pharmacology background.",
    education: { degree: "PhD Pharmacology", school: "Università di Bologna", year: 2012 },
    history: [
      { role: "Life-sciences Translator", org: "Freelance", from: 2014, to: null },
      { role: "Research Fellow", org: "Università di Bologna", from: 2012, to: 2014 },
    ],
  },
  {
    id: "APP-2027", name: "Daniel Kowalski", email: "d.kowalski@wp.pl",
    location: "Kraków, Poland", timezone: "CET (UTC+1)", appliedHoursAgo: 144,
    pairs: ["PL>EN"], specs: ["Technical"], years: 1, rate: 0.05,
    capacity: 5000, tools: ["Smartcat"], score: 61,
    verification: { identity: "verified", ata: "none", degree: "pending" },
    ataNumber: null, status: "rejected",
    rejectReason: "Assessment below threshold",
    summary: "Recent graduate translating software documentation from Polish into English.",
    education: { degree: "BA English Philology", school: "Jagiellonian University", year: 2024 },
    history: [
      { role: "Junior Translator", org: "Freelance", from: 2024, to: null },
    ],
  },
  {
    id: "APP-2026", name: "Ingrid Solberg", email: "ingrid.solberg@online.no",
    location: "Oslo, Norway", timezone: "CET (UTC+1)", appliedHoursAgo: 168,
    pairs: ["NO>EN", "SV>EN"], specs: ["Technical", "Energy"], years: 10, rate: 0.14,
    capacity: 10000, tools: ["memoQ", "Trados Studio"], score: 92,
    verification: { identity: "verified", ata: "verified", degree: "verified" },
    ataNumber: "ATA-240093", status: "approved",
    summary: "Offshore energy and renewables translator: HSE manuals, tender documentation and environmental impact assessments for Nordic operators.",
    education: { degree: "MSc Petroleum Engineering", school: "NTNU Trondheim", year: 2013 },
    history: [
      { role: "Technical Translator", org: "Freelance", from: 2016, to: null },
      { role: "Field Engineer", org: "Equinor", from: 2013, to: 2016 },
    ],
  },
];
