// Annie's Shoes World catalog. Each colorway drives the generated SVG artwork in shoe-art.js.
(function (root) {
  const PRODUCTS = [
    {
      id: "w-orbit-1",
      name: "Orbit One",
      brand: "Annie's",
      category: "Lifestyle",
      gender: "Unisex",
      silhouette: "low",
      price: 140,
      rating: 4.8,
      reviews: 312,
      tags: ["new", "hot"],
      sizes: [6, 7, 8, 9, 10, 11, 12, 13],
      soldOut: [13],
      description:
        "Our flagship low-top. Full-grain leather upper, cloud-foam midsole and a gum outsole built for all-day laps around the city.",
      colorways: [
        { name: "Volt Night", upper: "#111111", sole: "#f2f2f2", accent: "#d4ff3a", laces: "#d4ff3a" },
        { name: "Bone", upper: "#efe9dd", sole: "#c98d4b", accent: "#1b1b1b", laces: "#ffffff" },
        { name: "Ultraviolet", upper: "#5b2bff", sole: "#ffffff", accent: "#ff4fd8", laces: "#ffffff" },
      ],
    },
    {
      id: "w-apex-hi",
      name: "Apex Hi",
      brand: "Annie's",
      category: "Basketball",
      gender: "Men",
      silhouette: "high",
      price: 185,
      rating: 4.7,
      reviews: 204,
      tags: ["hot"],
      sizes: [8, 9, 10, 11, 12, 13, 14],
      soldOut: [8],
      description:
        "Lockdown high-top with a carbon shank, responsive heel pod and a herringbone outsole that grips like it owes you money.",
      colorways: [
        { name: "Chicago Heat", upper: "#d7263d", sole: "#ffffff", accent: "#111111", laces: "#ffffff" },
        { name: "Midnight", upper: "#14213d", sole: "#e5e5e5", accent: "#fca311", laces: "#fca311" },
      ],
    },
    {
      id: "s-vapor-run",
      name: "Vapor Run 3",
      brand: "Stratos",
      category: "Running",
      gender: "Women",
      silhouette: "runner",
      price: 160,
      salePrice: 119,
      rating: 4.6,
      reviews: 541,
      tags: ["sale"],
      sizes: [5, 6, 7, 8, 9, 10, 11],
      soldOut: [],
      description:
        "Featherweight engineered mesh and a plated supercritical foam stack. Race day energy, every day.",
      colorways: [
        { name: "Coral Rush", upper: "#ff6b6b", sole: "#fff4e6", accent: "#2ec4b6", laces: "#ffffff" },
        { name: "Glacier", upper: "#cde7f0", sole: "#ffffff", accent: "#0077b6", laces: "#0077b6" },
        { name: "Stealth", upper: "#2b2d42", sole: "#8d99ae", accent: "#ef233c", laces: "#edf2f4" },
      ],
    },
    {
      id: "k-zen-slip",
      name: "Zen Slip-On",
      brand: "Kōdo",
      category: "Lifestyle",
      gender: "Unisex",
      silhouette: "low",
      price: 95,
      rating: 4.4,
      reviews: 128,
      tags: [],
      sizes: [5, 6, 7, 8, 9, 10, 11, 12],
      soldOut: [5, 6],
      description:
        "Minimal canvas slip-on with a vulcanised sole and a cork-blend footbed that molds to you.",
      colorways: [
        { name: "Matcha", upper: "#8ab17d", sole: "#f8f4e3", accent: "#2a9d8f", laces: "#f8f4e3" },
        { name: "Sumi", upper: "#22223b", sole: "#f2e9e4", accent: "#c9ada7", laces: "#f2e9e4" },
      ],
    },
    {
      id: "r-kickflip-pro",
      name: "Kickflip Pro",
      brand: "Rift",
      category: "Skate",
      gender: "Men",
      silhouette: "low",
      price: 85,
      rating: 4.5,
      reviews: 389,
      tags: ["new"],
      sizes: [7, 8, 9, 10, 11, 12],
      soldOut: [],
      description:
        "Suede toe, triple-stitched ollie zone and a grippy waffle cupsole. Built to get shredded.",
      colorways: [
        { name: "Checker", upper: "#1d1d1d", sole: "#ffffff", accent: "#ffffff", laces: "#1d1d1d" },
        { name: "Mustard", upper: "#e9c46a", sole: "#fefae0", accent: "#264653", laces: "#264653" },
        { name: "Oxblood", upper: "#6a040f", sole: "#f1faee", accent: "#ffba08", laces: "#f1faee" },
      ],
    },
    {
      id: "n-ridge-trail",
      name: "Ridge GTX",
      brand: "Nomad Lab",
      category: "Trail",
      gender: "Unisex",
      silhouette: "runner",
      price: 175,
      rating: 4.9,
      reviews: 97,
      tags: ["hot"],
      sizes: [6, 7, 8, 9, 10, 11, 12, 13],
      soldOut: [12],
      description:
        "Waterproof membrane, rock plate and 5mm lugs. Goes from summit to street without blinking.",
      colorways: [
        { name: "Moss", upper: "#606c38", sole: "#283618", accent: "#dda15e", laces: "#fefae0" },
        { name: "Ember", upper: "#bc6c25", sole: "#3d2b1f", accent: "#fefae0", laces: "#fefae0" },
      ],
    },
    {
      id: "v-surge-hi",
      name: "Surge Hi",
      brand: "Volta",
      category: "Basketball",
      gender: "Women",
      silhouette: "high",
      price: 150,
      salePrice: 105,
      rating: 4.3,
      reviews: 76,
      tags: ["sale"],
      sizes: [5, 6, 7, 8, 9, 10],
      soldOut: [],
      description:
        "Retro court energy with a padded collar, ankle strap and a cushioned air-cell heel.",
      colorways: [
        { name: "Bubblegum", upper: "#ffafcc", sole: "#ffffff", accent: "#7b2cbf", laces: "#ffffff" },
        { name: "Mint Chip", upper: "#b8f2e6", sole: "#ffffff", accent: "#3a3a3a", laces: "#3a3a3a" },
      ],
    },
    {
      id: "w-drift-runner",
      name: "Drift Runner",
      brand: "Annie's",
      category: "Running",
      gender: "Men",
      silhouette: "runner",
      price: 130,
      rating: 4.6,
      reviews: 266,
      tags: ["new"],
      sizes: [7, 8, 9, 10, 11, 12, 13],
      soldOut: [7],
      description:
        "Daily trainer with a rocker geometry and knit upper. Long runs feel short.",
      colorways: [
        { name: "Solar", upper: "#ff7b00", sole: "#1a1a1a", accent: "#ffffff", laces: "#1a1a1a" },
        { name: "Arctic", upper: "#f8f9fa", sole: "#adb5bd", accent: "#4361ee", laces: "#4361ee" },
      ],
    },
    {
      id: "s-cloud-walk",
      name: "Cloudwalk",
      brand: "Stratos",
      category: "Lifestyle",
      gender: "Women",
      silhouette: "low",
      price: 110,
      rating: 4.5,
      reviews: 418,
      tags: [],
      sizes: [5, 6, 7, 8, 9, 10, 11],
      soldOut: [11],
      description:
        "Chunky platform sole, buttery nubuck and a soft-touch lining. Height and comfort, no compromises.",
      colorways: [
        { name: "Lilac", upper: "#cdb4db", sole: "#ffffff", accent: "#ffc8dd", laces: "#ffffff" },
        { name: "Sand", upper: "#e9d8a6", sole: "#ffffff", accent: "#94d2bd", laces: "#ffffff" },
      ],
    },
    {
      id: "r-grind-mid",
      name: "Grind Mid",
      brand: "Rift",
      category: "Skate",
      gender: "Unisex",
      silhouette: "high",
      price: 99,
      salePrice: 79,
      rating: 4.2,
      reviews: 143,
      tags: ["sale"],
      sizes: [6, 7, 8, 9, 10, 11, 12],
      soldOut: [6],
      description:
        "Mid-cut ankle support, padded tongue and an abrasion-resistant toe wrap for long sessions.",
      colorways: [
        { name: "Forest", upper: "#2d6a4f", sole: "#f1faee", accent: "#e63946", laces: "#f1faee" },
        { name: "Ink", upper: "#03045e", sole: "#caf0f8", accent: "#00b4d8", laces: "#caf0f8" },
      ],
    },
    {
      id: "k-tatami",
      name: "Tatami Court",
      brand: "Kōdo",
      category: "Lifestyle",
      gender: "Men",
      silhouette: "low",
      price: 125,
      rating: 4.7,
      reviews: 59,
      tags: ["new"],
      sizes: [7, 8, 9, 10, 11, 12],
      soldOut: [],
      description:
        "Clean tennis-inspired profile with woven rush detailing and a sustainably-sourced rubber cup.",
      colorways: [
        { name: "Washi", upper: "#fdfcdc", sole: "#fed9b7", accent: "#f07167", laces: "#fdfcdc" },
        { name: "Indigo", upper: "#3d405b", sole: "#f4f1de", accent: "#e07a5f", laces: "#f4f1de" },
      ],
    },
    {
      id: "n-basecamp",
      name: "Basecamp Hi",
      brand: "Nomad Lab",
      category: "Trail",
      gender: "Men",
      silhouette: "high",
      price: 210,
      rating: 4.8,
      reviews: 88,
      tags: [],
      sizes: [8, 9, 10, 11, 12, 13],
      soldOut: [13],
      description:
        "Hiker-sneaker hybrid with a gusseted tongue, speed-hook lacing and a vibram-style outsole.",
      colorways: [
        { name: "Granite", upper: "#495057", sole: "#212529", accent: "#ffd60a", laces: "#ffd60a" },
        { name: "Dune", upper: "#d4a373", sole: "#6c584c", accent: "#283618", laces: "#283618" },
      ],
    },
    {
      id: "v-flash-xr",
      name: "Flash XR",
      brand: "Volta",
      category: "Running",
      gender: "Unisex",
      silhouette: "runner",
      price: 200,
      rating: 4.9,
      reviews: 172,
      tags: ["hot", "new"],
      sizes: [6, 7, 8, 9, 10, 11, 12, 13],
      soldOut: [],
      description:
        "Our fastest shoe ever. Dual carbon plates, 40mm of hyper-foam and a translucent speed upper.",
      colorways: [
        { name: "Hyperpink", upper: "#ff006e", sole: "#ffbe0b", accent: "#3a86ff", laces: "#ffffff" },
        { name: "Electric", upper: "#3a86ff", sole: "#ffffff", accent: "#ffbe0b", laces: "#ffffff" },
      ],
    },
    {
      id: "w-legacy-74",
      name: "Legacy '74",
      brand: "Annie's",
      category: "Lifestyle",
      gender: "Women",
      silhouette: "low",
      price: 120,
      salePrice: 89,
      rating: 4.4,
      reviews: 230,
      tags: ["sale"],
      sizes: [5, 6, 7, 8, 9, 10],
      soldOut: [10],
      description:
        "Archive runner revived. Suede overlays, nylon panels and a vintage-yellowed midsole.",
      colorways: [
        { name: "Varsity", upper: "#1d3557", sole: "#f1e3c6", accent: "#e63946", laces: "#f1e3c6" },
        { name: "Sage", upper: "#a3b18a", sole: "#f1e3c6", accent: "#344e41", laces: "#f1e3c6" },
      ],
    },
    {
      id: "s-aero-court",
      name: "Aero Court",
      brand: "Stratos",
      category: "Basketball",
      gender: "Unisex",
      silhouette: "high",
      price: 165,
      rating: 4.5,
      reviews: 134,
      tags: [],
      sizes: [7, 8, 9, 10, 11, 12, 13, 14],
      soldOut: [14],
      description:
        "Guard-friendly hoops shoe with a low-to-ground feel and a lateral outrigger for hard cuts.",
      colorways: [
        { name: "Royal", upper: "#023e8a", sole: "#ffffff", accent: "#ffffff", laces: "#ffffff" },
        { name: "Blackout", upper: "#0b090a", sole: "#161a1d", accent: "#e5383b", laces: "#e5383b" },
      ],
    },
    {
      id: "r-bowl-low",
      name: "Bowl Low",
      brand: "Rift",
      category: "Skate",
      gender: "Women",
      silhouette: "low",
      price: 80,
      rating: 4.3,
      reviews: 64,
      tags: ["new"],
      sizes: [5, 6, 7, 8, 9, 10],
      soldOut: [],
      description:
        "Slim vulc profile with board feel for days and a reinforced lace channel.",
      colorways: [
        { name: "Peach", upper: "#ffb4a2", sole: "#ffffff", accent: "#6d6875", laces: "#ffffff" },
        { name: "Lagoon", upper: "#48cae4", sole: "#ffffff", accent: "#023e8a", laces: "#ffffff" },
      ],
    },
  ];

  const PROMO_CODES = {
    ANNIE10: { type: "percent", value: 10, label: "10% off" },
    FRESHKICKS: { type: "flat", value: 20, label: "$20 off" },
  };

  const exportsObj = { PRODUCTS, PROMO_CODES };
  if (typeof module !== "undefined" && module.exports) module.exports = exportsObj;
  else Object.assign(root, exportsObj);
})(typeof window !== "undefined" ? window : globalThis);
